---
- name: Install Java
  hosts: local
  tasks:
    - name: Set facts for Java 11 vars
      ansible.builtin.set_fact:
        java_home: "/opt/jdk/{{ java_jdk_version }}"
      tags: java
    - name: Download java from remote URL
      get_url:
        url: "https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/download/jdk-11.0.15%2B10/OpenJDK11U-jdk_x64_linux_11.0.15_10.tar.gz"
        dest: "/tmp/jdk-{{ java_jdk_version }}.tar.gz"
        mode: 0755
        timeout: 60
        force: true
        validate_certs: false
      register: download_java_binaries
      until: download_java_binaries is succeeded
      tags: java
    - name: Creates tmp directory 
      file:
      path: /tmp/
      state: directory
    - name: Ensure installation dir exists
      become: true
      ansible.builtin.file:
        state: directory
        path: "{{ java_home }}"
        mode: '755'
      tags: java
    - name: Extract java in the installation directory
      become: true
      ansible.builtin.unarchive:
        copy: false
        src: "/tmp/jdk-{{ java_jdk_version }}.tar.gz"
        dest: "{{ java_home }}"
        extra_opts: [--strip-components=1]
        creates: "{{ java_home }}/bin/java"
        mode: '755'
      tags:
        - java
    - name: Export environment variables
      become: true
      ansible.builtin.template:
        src: jdk.sh.j2
        dest: /etc/profile.d/jdk.sh
        mode: '755'
      tags: java
- name: Install Elasticsearch
  hosts: local
  become: yes
  tasks:
    - name: Upload tar.gz Elasticsearch from remote URL
#      get_url:
#        url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elastic_version }}-linux-x86_64.tar.gz"
#        dest: "/tmp/elasticsearch-{{ elastic_version }}-linux-x86_64.tar.gz"
#        mode: 0755
#        timeout: 60
#        force: true
#        validate_certs: false
      ansible.builtin.copy:
        src: "elasticsearch-{{ elastic_version }}-linux-x86_64.tar.gz"
        dest: "/tmp/elasticsearch-{{ elastic_version }}-linux-x86_64.tar.gz"
        mode: '644'
      register: get_elastic
      until: get_elastic is succeeded
      tags: elastic
    - name: Create directrory for Elasticsearch
      ansible.builtin.file:
        state: directory
        path: "{{ elastic_home }}"
        mode: '755'
      tags: elastic
    - name: Extract Elasticsearch in the installation directory
      become: true
      ansible.builtin.unarchive:
        copy: false
        src: "/tmp/elasticsearch-{{ elastic_version }}-linux-x86_64.tar.gz"
        dest: "{{ elastic_home }}"
        extra_opts: [--strip-components=1]
        creates: "{{ elastic_home }}/bin/elasticsearch"
        mode: '755'
      tags:
        - elastic
    - name: Set environment Elastic
      become: true
      ansible.builtin.template:
        src: templates/elk.sh.j2
        dest: /etc/profile.d/elk.sh
        mode: '755'
      tags: elastic
####
- name: Install kibana
  hosts: local
  become: yes
  tasks:
    - name: Upload tar.gz kibana from remote URL
      ansible.builtin.copy:
        src: "kibana-{{ elastic_version }}-linux-x86_64.tar.gz"
        dest: "/tmp/kibana-{{ elastic_version }}-linux-x86_64.tar.gz"
        mode: '644'
      register: get_kibana
      until: get_kibana is succeeded
      tags: kibana
    - name: Create directrory for kibana
      ansible.builtin.file:
        state: directory
        path: "{{ kibana_home }}"
        mode: '755'
      tags: kibana
    - name: Extract kibana in the installation directory
      become: true
      ansible.builtin.unarchive:
        copy: false
        src: "/tmp/kibana-{{ elastic_version }}-linux-x86_64.tar.gz"
        dest: "{{ kibana_home }}"
        extra_opts: [--strip-components=1]
        creates: "{{ kibana_home }}/bin/kibana"
        mode: '755'
      tags:
        - kibana
    - name: Set environment kibana
      become: true
      ansible.builtin.template:
        src: templates/elk.sh.j2
        dest: /etc/profile.d/elk.sh
        mode: '755'
      tags: kibana
